### PR TITLE
2.1 awiesm 2.1

### PR DESCRIPTION
**Pull request by ackerlar**
iceberg related changes from the gitlab fesom version

### CODE REVIEW

**Comment by mandresm** [comment]
This PR potentially broke AWIESM-2.1 with icebergs in Ollie. The problem is that fesom is not producing the `iceberg.restart.ISM` anywhere and then the first `tidy` step fails with the following error:

```
========================================================================================
::: Executing the step:  copy_files_to_thisrun    (step [9/15] of the job:  prepcompute)
========================================================================================
PREPARING EXPERIMENT

- File lists populated, proceeding with copy...
- Note that you can see your file lists in the config folder
- You will be informed about missing files 
Traceback (most recent call last):
  File "/home/ollie/mandresm/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/cli.py", line 278, in main
    Setup()
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 152, in maybe_resubmit
    nextrun = resubmit_recursively(config, jobtype=jobtype)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 193, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 70, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/sim_objects.py", line 90, in __call__
    resubmit.maybe_resubmit(self.config)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 169, in maybe_resubmit
    config, list_of_clusters=[cluster], nextrun_in=True
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 193, in resubmit_recursively
    resubmit_SimulationSetup(config, cluster)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/resubmit.py", line 70, in resubmit_SimulationSetup
    config["general"]["experiment_over"] = cluster_obj(kill_after_submit=False)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/prepcompute.py", line 36, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    framework_recipe, framework_plugins, config
  File "/home/ollie/mandresm/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/ollie/mandresm/esm_tools/src/esm_runscripts/prepcompute.py", line 238, in copy_files_to_thisrun
    num_lines = sum(1 for line in open(os.path.join(config["fesom"]["experiment_restart_in_dir"], "iceberg.restart.ISM")))
FileNotFoundError: [Errno 2] No such file or directory: '/work/ollie/mandresm/testing//run/awiesm//awiesm-2.1_icebergs/restart/fesom/iceberg.restart.ISM'
```

**Comment by ackerlar** [comment]
Which esm_tools version are you using? So it doesn't even start the first year?

**Comment by mandresm** [comment]
I'm using the latest version. It does start the first year but it crashes at the end of it, in the tidying part. Can run it with your version of ESM-Tools without problems?

**Comment by ackerlar** [comment]
For me it works:
/work/ba0989/a270124/direnv_test/experiments/icb_test10
`feat/dual_hemisphere`

**Comment by mandresm** [comment]
Which ESM-Tools version and branch?

**Comment by ackerlar** [comment]
Ah sorry, the branch is `feat/dual_hemisphere` but the differences to `release` are only PISM related. Should be version 6.8.0.

**Comment by mandresm** [comment]
The `fesom-2.1.yaml` in `release` and `feat/dual_hemisphere` are quite different. It looks to me like your version is prior to our cleanup of AWIESM files, where we made sure not only icebergs worked, but also that in the part of icebergs the unnecessary complexity was reduced. I think the differences are normal as I suspect `feat/dual_hemisphere` probably comes from AWIESM with PISM which was never merge to release (sorry about that... one day soon...)

In any case, no iceberg restart file is produced. I suspect that's because there has been some changes in the namelists for activating icebergs, and those changes have not been implemented in ESM-Tools release. Can you provide a path to one of your working experiments?

**Comment by ackerlar** [comment]
A path is here: /work/ba0989/a270124/direnv_test/experiments/icb_test10
It runs into a time out after the job already finished, but it writes 'iceberg.restart.ISM'

**Comment by pgierz** [comment]
I can have a deeper look at the beginning of next week, unless someone else wants to take this one.

**Comment by pgierz** [comment]
I can have a deeper look at this on Monday unless someone else wants to take it.

**Comment by pgierz** [comment]
Also, this looks more like a problem in the esm tools side, I think fesom is fine...

**Comment by mandresm** [comment]
great, thanks :)

**Comment by ackerlar** [comment]
Sorry guys, the `feat/dual_hemisphere` on the repository is very outdated... 
I just pushed the one, that I actually use: [https://github.com/esm-tools/esm_tools/tree/feat/dual_hemisphere-levante](url)
Sorry for the confusion

**Comment by koldunovn** [comment]
If problem solved, please close the issue :)

**Comment by pgierz** [comment]
Closing, I'll make a correct issue on esm tools on Monday. @koldunovn Seems to be on a cleaning spree ;-)

**Pull request merged**
