### PR TITLE
Rename main source file

### PR DESCRIPTION
**Pull request by hegish**

### CODE REVIEW

**Comment by hegish** [comment]
Hey @koldunovn and @dsidoren, when I did the pull request, everything was fine. Should I merge with refactoring to resolve the issue?

**Comment by koldunovn** [comment]
Hi Jan, yes, since we changing refactoring so often it's a good idea to pull often :)

**Comment by hegish** [comment]
> Hi Jan, yes, since we changing refactoring so often it's a good idea to pull often :)

I did not change anything since the pull request. There was no conflict then. If I update everything now, the same might happen again. So maybe you could tell me when merging should happen and I can resolve any conflicts right then.

**Comment by dsidoren** [comment]
> > Hi Jan, yes, since we changing refactoring so often it's a good idea to pull often :)
> 
> I did not change anything since the pull request. There was no conflict then. If I update everything now, the same might happen again. So maybe you could tell me when merging should happen and I can resolve any conflicts right then.

Looks very strange. Let Nikolay resolve it!

**Comment by hegish** [comment]
Ui, sorry for the confusion. I would gladly have re-merged it myself. Glad you also merged it to master, @dsidoren 👍

**Pull request merged**
