### PR TITLE
integrate master with openacc

### PR DESCRIPTION
**Pull request by dguibert**
This PR integrates the merge of master into pgi-fixes and adds some commits to get FESOM compile with the PGI compiler.

I propose this to the `pgi-fixes` branch but it could be merged into `master` as without any support of OpenACC directives it behaves as usual.

### CODE REVIEW

**Comment by koldunovn** [comment]
@dguibert We can't test it for the `pgi-fixes` branch, so it you think it's OK, I can just merge it. This might make it easier to work further on the openACC, right?

**Comment by dguibert** [comment]
Yes, I'll continue to work on Gijs' modifications on the branch.

I was wondering if you would test that FESOM compiles on top of this commit within your CPU environment and test cases.

**Comment by koldunovn** [comment]
@dguibert I can do that, sure. Will take a couple of days though - there is a conference going on, so we are bit slow with things now :)

**Comment by koldunovn** [comment]
I did check it on several our systems, everything works fine. Should I merge?

**Comment by goord** [comment]
Hi @dguibert and @koldunovn I have committed a few more fixes to this branch, necessary to make it run on juwels-booster (see #59). I think we now have a starting point to merge and continue to work on the OpenACC version.

**Comment by koldunovn** [comment]
Hi @dguibert and @goord . There is a conflict now, once you fix it I will test and merge :)

**Comment by dguibert** [comment]
> Hi @dguibert and @goord . There is a conflict now, once you fix it I will test and merge :)

@goord if you could test it on juwels-booster?

**Comment by goord** [comment]
@dguibert I have tested the merged branch on juwels-booster and I have pushed a fix to make it work. The new branch is a bit slower overall than the umbers reported in discussion #59 but openacc still provides a 10% speedup of the tracer part and 4% overall

**Comment by koldunovn** [comment]
@goord @dguibert What is the status now? Do you still plan to merge it? Probably, since you both are now can create branches here you can do it yourself when ready. Or just let me know if I should do it ;)

**Comment by dguibert** [comment]
@goord Are you ok if I resolve the conflicts and merge this to the `pgi-fixes` branch?

PS: Maybe we could rename it to `openacc` afterwards.

**Comment by goord** [comment]
Yes that's fine, and I agree with the renaming too!

**Comment by goord** [comment]
Hi @dguibert I have integrated your conflict merges in a new merge that I just pushed to the ``pgi-fixes`` branch. I have updated many of the accelerated loops and I am testing it now.

**Comment by dguibert** [comment]
> Hi @dguibert I have integrated your conflict merges in a new merge that I just pushed to the `pgi-fixes` branch. I have updated many of the accelerated loops and I am testing it now.

Hi @goord, could you please test on top of the newly uploaded `dg/integrate-master-with-openacc` ([ESIWACE-S1/fesom2](https://github.com/ESiWACE-S1/fesom2) )? It contains my merges and yours ;-)

CORE2 and STORM test cases are working (they finish fine).
But  when I'm using `srun nsys profile --stats=true -f true -t cuda,openacc,nvptx fesom` on juwels-booster
- it works on core2 (40 tasks)
- it fails on storm (288 tasks)
Could you check if you reproduce those observations?

**Comment by goord** [comment]
> > Hi @dguibert I have integrated your conflict merges in a new merge that I just pushed to the `pgi-fixes` branch. I have updated many of the accelerated loops and I am testing it now.
> 
> Hi @goord, could you please test on top of the newly uploaded `dg/integrate-master-with-openacc` ([ESIWACE-S1/fesom2](https://github.com/ESiWACE-S1/fesom2) )? It contains my merges and yours ;-)
> 
> CORE2 and STORM test cases are working (they finish fine).
> But when I'm using `srun nsys profile --stats=true -f true -t cuda,openacc,nvptx fesom` on juwels-booster
> 
> * it works on core2 (40 tasks)
> * it fails on storm (288 tasks)
>   Could you check if you reproduce those observations?

I see you fixed the missing pointer association that I forgot. I can confirm that the test cases run successfully. The profiling command seems to fail because of the nvptx option (needs to be nvtx?)

**Comment by dguibert** [comment]
Thanks for merging and confirm it work.

> The profiling command seems to fail because of the nvptx option (needs to be nvtx?)

yes, copy/paste mistake. It should be `nvtx` (and it's on my script for storm)

**Pull request merged**
