### PR TITLE
Delete content in view_pscholz

### PR DESCRIPTION
**Pull request by patrickscholz**
- Delete the old python routines in view_pscholz (haven't supported them for a while) and replace them with a readme file how to get to tripyview (the stuff i keep upto date in moment)
- No Changes to the rest of the code!

### CODE REVIEW

**Comment by koldunovn** [comment]
@patrickscholz Maybe we can move the text to the main README and spare ourselves a directory? Like add "visualization" section to the end of the README, and maybe also add such a section in the main documentation with links to `tripyview`, `pyfesom2` and `spheRlab`?

**Comment by koldunovn** [comment]
Yes, having a folder is a good idea. So we can rename `view` to  `visualization`, keep Dima's things in there and add README with links to separate viz tools. Does it sounds OK?

**Comment by patrickscholz** [comment]
Yes, i think that is the best way to go, i can add this to this pull request in the weekend or next week.

**Comment by koldunovn** [comment]
OK to merge?

**Comment by patrickscholz** [comment]
@koldunovn  I think so !

**Review by koldunovn — APPROVED** [review]

**Pull request merged**
