### PR TITLE
[WIP] use the right interface, explicit interface was already set

### PR DESCRIPTION
**Pull request by trackow**
@JanStreffing Could you try whether this fixes the issue on aleph?

### CODE REVIEW

**Comment by JanStreffing** [comment]
Hey @trackow,
that seems to help some. I got to 95% using https://github.com/FESOM/fesom2/tree/fix-explicitinterface-aleph time before getting this error:
```

[ 95%] Building Fortran object src/CMakeFiles/fesom.dir/oce_ale.F90.o


ftn-855 crayftn: ERROR DIAGNOSTICS, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 1, Column = 8 
  The compiler has detected errors in module "DIAGNOSTICS".  No module information file will be created for this module.


ftn-113 crayftn: ERROR DIAG_DENSMOC, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 455, Column = 253 
  IMPLICIT NONE is specified in the local scope, therefore an explicit type must be specified for data object "ELN".


ftn-1725 crayftn: ERROR DIAG_DENSMOC, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 455, Column = 256 
  Unexpected syntax while parsing the assignment statement : ")" was expected but found "EOS".


ftn-1725 crayftn: ERROR DIAG_DENSMOC, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 455, Column = 256 
  Unexpected syntax while parsing the assignment statement : ")" was expected but found "EOS".


ftn-1725 crayftn: ERROR DIAG_DENSMOC, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 455, Column = 256 
  Unexpected syntax while parsing the assignment statement : ")" was expected but found "EOS".


ftn-1725 crayftn: ERROR DIAG_DENSMOC, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/gen_modules_diag.F90, Line = 455, Column = 256 
  Unexpected syntax while parsing the assignment statement : ")" was expected but found "EOS".

Cray Fortran : Version 8.7.5 (20180919174803_65a0fd5d93d142733c36203b4453f8bccc07a569)
Cray Fortran : Mon Mar 29, 2021  19:45:08
Cray Fortran : Compile time:  0.1472 seconds
Cray Fortran : 1797 source lines
Cray Fortran : 6 errors, 0 warnings, 0 other messages, 0 ansi
Cray Fortran : "explain ftn-message number" gives more information about each message.
src/CMakeFiles/fesom.dir/build.make:537: recipe for target 'src/CMakeFiles/fesom.dir/gen_modules_diag.F90.o' failed
make[2]: *** [src/CMakeFiles/fesom.dir/gen_modules_diag.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....


ftn-7220 crayftn: WARNING VERT_VEL_ALE, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/oce_ale.F90, Line = 1869 
  The array syntax statement may not be conformable.

CMakeFiles/Makefile2:99: recipe for target 'src/CMakeFiles/fesom.dir/all' failed
make[1]: *** [src/CMakeFiles/fesom.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by trackow** [comment]
Oh my, I have an idea what that is... One second

**Comment by trackow** [comment]
Can you try again? :)

**Comment by trackow** [comment]
For the warning in vert_vel_ale, it seems to me that the arrays are not of same length:

The commented line went from 1:lzstar_lev or from 2:lzstar_lev+1 (same length, shifted one):
_!max_dhbar2distr = (zbar(1:lzstar_lev)-zbar(2:lzstar_lev+1))*min_hnode - hnode(1:lzstar_lev,n);_

The uncommented line goes from nzmin:nzmin+lzstar_lev-1, or from nzmin:nzmin+lzstar_lev (one more entry)
_max_dhbar2distr = (zbar(nzmin:nzmin+lzstar_lev-1)-zbar(nzmin:nzmin+lzstar_lev-1+1))*min_hnode - hnode(nzmin:nzmin+lzstar_lev-1,n);_

Without knowing what happens here, my guess would be that this line (nzmin+1:nzmin+lzstar_lev-1+1 in second array) might be more correct @patrickscholz @dsidoren ?
max_dhbar2distr = (zbar(nzmin:nzmin+lzstar_lev-1)-zbar(nzmin+1:nzmin+lzstar_lev-1+1))*min_hnode - hnode(nzmin:nzmin+lzstar_lev-1,n);

**Comment by patrickscholz** [comment]
Hi Thomas 

So the part you mentioned should only account for the zlevel case, where originally the change in ssh should be distributed within the first layer. The  problem here can be when the first layer is rather thin and the change in ssh is large (e.g large freshwaterinput) that the first layerthickness can be flattened out (goes to zeros or becomes negative) and the model would inevitably blowup. To prevent this, i tried to allow the zlevel mode to switch from zlevel towards a local zstar approach and allow locally to distribute ssh over the first 3 or 5 layers. 
Nevertheless, we recommend using zstar anyway. Lately i also focused more on zstar to get things working and neglected a bit zlevel.  But i will check on this line when i have time.

**Comment by patrickscholz** [comment]
Yes you are fully right! I will change it directly in the master

**Comment by JanStreffing** [comment]
> Can you try again? :)

on https://github.com/FESOM/fesom2/tree/fix-explicitinterface-aleph ?

**Comment by JanStreffing** [comment]
Getting warmer, 98% now ;-)

```
[ 97%] Building Fortran object src/CMakeFiles/fesom.dir/write_step_info.F90.o
[ 98%] Building Fortran object src/CMakeFiles/fesom.dir/gen_model_setup.F90.o


ftn-828 crayftn: ERROR BC_SURFACE, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/oce_ale_tracer.F90, Line = 1005, Column = 21 
  Procedure "BC_SURFACE" is defined in multiple places.  Argument 1 has INTENT(IN) in one definition but not the other.


ftn-828 crayftn: ERROR BC_SURFACE, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/oce_ale_tracer.F90, Line = 1005, Column = 24 
  Procedure "BC_SURFACE" is defined in multiple places.  Argument 2 has INTENT(IN) in one definition but not the other.

src/CMakeFiles/fesom.dir/build.make:953: recipe for target 'src/CMakeFiles/fesom.dir/oce_ale_tracer.F90.o' failed
make[2]: *** [src/CMakeFiles/fesom.dir/oce_ale_tracer.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....


ftn-7220 crayftn: WARNING VERT_VEL_ALE, File = ../../../mnt/lustre/home/awiiccp2/esm/model_codes/awicm3-1.0-deck/fesom-2.0/src/oce_ale.F90, Line = 1869 
  The array syntax statement may not be conformable.

CMakeFiles/Makefile2:99: recipe for target 'src/CMakeFiles/fesom.dir/all' failed
make[1]: *** [src/CMakeFiles/fesom.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by JanStreffing** [comment]
I added an intent(in) in:
https://github.com/FESOM/fesom2/blob/8781b64a696487f451cdd98c3500a4fcd760b855/src/oce_ale_tracer.F90#L1015

I was able to compile the routine and the whole model.

**Comment by patrickscholz** [comment]
Yes wanted to tell you the same!

**Comment by trackow** [comment]
Sounds great, I am glad this all worked so smoothly! Please let me know if there is anything else cray-specific when you run the model :-)

**Comment by JanStreffing** [comment]
We ended up merged, combined with a few other changes in #102
I propose to close this issue here.

**Comment by koldunovn** [comment]
This is already part of #102 that was merged to master, so I suggest we close it?

**Pull request closed without merging**
