### PR TITLE
Fluxpaper/ocurrf+nohem+refac+spp+bugfixpscholz

### PR DESCRIPTION
**Pull request by JanStreffing**
The OMP test passes: https://github.com/FESOM/fesom2/actions/runs/2486894214
The MPI test does not: https://github.com/FESOM/fesom2/runs/6857263048?check_suite_focus=true

```
 /__w/fesom2/fesom2/src/ice_thermo_cpl.F90:198:5:
  198 |      residualifwflx(inod) = resid
      |     1
Error: Unclassifiable statement at (1)
```

@dsidoren What do you think about this implementation. It's a bit more verbose that what I had done, but perhaps that's not a bad thing.

### CODE REVIEW

**Comment by JanStreffing** [comment]
Ty @patrickscholz 
The tests are now failing with:

Traceback (most recent call last):
```
Variable: a_ice, current_value: 0.26923890674496553, master_value: 0.2692498167543513
  File "/opt/miniconda3/bin/fcheck", line 33, in <module>
FAIL!!!: a_ice DIFFERENCE: -1.0910009385745045e-05.
    sys.exit(load_entry_point('mkfesom', 'console_scripts', 'fcheck')())
  File "/fesom/mkfesom/mkfesom/fcheck.py", line 66, in fcheck
Variable: salt, current_value: 23.94410229501732, master_value: 23.94408981205545
    raise AssertionError("One or several tests have failed.")
FAIL!!!: salt DIFFERENCE: 1.248296187128517e-05.
AssertionError: One or several tests have failed.
Variable: sst, current_value: 8.527245288712482, master_value: 8.526792796340805
FAIL!!!: sst DIFFERENCE: 0.0004524923716768825.
Variable: temp, current_value: 1.7017988788743155, master_value: 1.7018189804276316
FAIL!!!: temp DIFFERENCE: -2.0101553316109744e-05.
Variable: u, current_value: -0.0014307222786612821, master_value: -0.0014310701355284
FAIL!!!: u DIFFERENCE: 3.478568671177757e-07.
Variable: v, current_value: 0.00014323982250421654, master_value: 0.0001431423767448
FAIL!!!: v DIFFERENCE: 9.744575941652992e-08.
```

I'll have a look for the culprit, and whether this is necessary after the AWI-CM3 meeting.

**Comment by JanStreffing** [comment]
Closes #348

**Review by dsidoren — APPROVED** [review]

**Comment by dsidoren** [comment]
> The OMP test passes: https://github.com/FESOM/fesom2/actions/runs/2486894214 The MPI test does not: https://github.com/FESOM/fesom2/runs/6857263048?check_suite_focus=true
> 
> ```
>  /__w/fesom2/fesom2/src/ice_thermo_cpl.F90:198:5:
>   198 |      residualifwflx(inod) = resid
>       |     1
> Error: Unclassifiable statement at (1)
> ```
> 
> @dsidoren What do you think about this implementation. It's a bit more verbose that what I had done, but perhaps that's not a bad thing.

**Comment by dsidoren** [comment]
> The OMP test passes: https://github.com/FESOM/fesom2/actions/runs/2486894214 The MPI test does not: https://github.com/FESOM/fesom2/runs/6857263048?check_suite_focus=true
> 
> ```
>  /__w/fesom2/fesom2/src/ice_thermo_cpl.F90:198:5:
>   198 |      residualifwflx(inod) = resid
>       |     1
> Error: Unclassifiable statement at (1)
> ```
> 
> @dsidoren What do you think about this implementation. It's a bit more verbose that what I had done, but perhaps that's not a bad thing.

**Comment by dsidoren** [comment]
> The OMP test passes: https://github.com/FESOM/fesom2/actions/runs/2486894214 The MPI test does not: https://github.com/FESOM/fesom2/runs/6857263048?check_suite_focus=true
> 
> ```
>  /__w/fesom2/fesom2/src/ice_thermo_cpl.F90:198:5:
>   198 |      residualifwflx(inod) = resid
>       |     1
> Error: Unclassifiable statement at (1)
> ```
> 
> @dsidoren What do you think about this implementation. It's a bit more verbose that what I had done, but perhaps that's not a bad thing.



> The OMP test passes: https://github.com/FESOM/fesom2/actions/runs/2486894214 The MPI test does not: https://github.com/FESOM/fesom2/runs/6857263048?check_suite_focus=true
> 
> ```
>  /__w/fesom2/fesom2/src/ice_thermo_cpl.F90:198:5:
>   198 |      residualifwflx(inod) = resid
>       |     1
> Error: Unclassifiable statement at (1)
> ```
> 
> @dsidoren What do you think about this implementation. It's a bit more verbose that what I had done, but perhaps that's not a bad thing.

checked, looks good! Shall be also applied in AWICM2 so maybe __oasis (not only __oifs) directive is even more appropriate  (let us keep it in mind).

**Pull request merged**
