### PR TITLE
Merging fesom branch in awicm3-v3.0 with latest fesom changes

### PR DESCRIPTION
**Pull request by mathanase**
Merging branches in order to integrate the latest fesom2 changes in the branch used in awicm3-v3.0

### CODE REVIEW

**Comment by hegish** [comment]
is there only one changed file?

**Comment by hegish** [comment]
I am not sure what the goal is here. Is it only the mkdir think? I could add these changes to the awicm3-frontiers-freeze-candidate-5 branch. Or should the awicm3-frontiers-freeze-candidate-5 branch also be up to date with all other changes in awicm-3-frontiers_parallel-restart?

**Comment by mandresm** [comment]
I think the merge should be the other way around: `awicm-3-frontiers_parallel-restart` into `awicm3-frontiers-freeze-candidate-5`. @hegish , I think you are right, the only thing needed here is the mkdir changes, or all the changes necessary for getting rid of the restarting writing problems.

**Comment by mathanase** [comment]
I am not quite sure actually. Maybe @JanStreffing would know better.

**Comment by JanStreffing** [comment]
Ok I had a look. This is indeed the wrong way round. It's a merger of a branch that has been frozen since September into the one that @hegish is developing IO solutions in. I will close this here and make a reversed merge request. Then we have to check if we want everything in `awicm-3-frontiers_parallel-restart `for the physics frozen `awicm3-frontiers-freeze-candidate-5`, or if some things would have the model results.

**Pull request closed without merging**
