### PR TITLE
do not allow to add the same variable name multiple times to the outp…

### PR DESCRIPTION
**Pull request by hegish**
…ut variables (io streams), e.g. via duplicates in namelist.io

### CODE REVIEW

**Comment by koldunovn** [comment]
Related to https://github.com/FESOM/fesom2/projects/1#card-54565263 and #69

**Comment by koldunovn** [comment]
Jan, thanks a lot! I will do the testing this week (need some time after holidays :))

**Comment by koldunovn** [comment]
@hegish I expand a bit the error message and make it print only once. If it's fine with you I will merge, everything works as expected! 👍

**Comment by hegish** [comment]
Hi @koldunovn, regarding the error only from process 0:
I would not do it since we do not know if all processes participate in I/O activity. We also should not optimize for a failure case with additional code. I would not recommend it.
Regarding the extended error message: This is good, but we might not always add I/O streams from namelist only, but also just via the add stream API. I think this might help to understand the cause of the error. I would change "define it two times" to "define it multiple times", though.

**Comment by koldunovn** [comment]
@hegish Point taken :) I remove the output only for `mype==0` and modify the message. It will clatter stdout with a bunch of messages, but I guess it's a rare case anyway :) Is it OK to merge form your perspective now?

**Comment by hegish** [comment]
Looks good! I can not hit the approve button of the PR, maybe because I filed it...

**Pull request merged**
