### PR TITLE
Ice fct screening

### PR DESCRIPTION
**Pull request by dsidoren**

### CODE REVIEW

**Comment by JanStreffing** [comment]
Change target to refactoring and redo.

**Review by JanStreffing — APPROVED** [review]

**Comment by JanStreffing** [comment]
@koldunov, could you evaluate and compare
`/work/ab0246/a270092/runtime/fesom-2.5-refactoring/reference/outdata/fesom/`
and
`/work/ab0246/a270092/runtime/fesom-2.5-refactoring/ice_fct_screening/outdata/fesom/` 
?

**Comment by JanStreffing** [comment]
Here is the tripyview evaluation of a 1958 to 2017 standalone core2 run with the ice FCT vs the same period with the current main branch. I have nowhere to host the html, so as a pdf instead:
[fesom26rc_ice_fct_screening.pdf](https://github.com/user-attachments/files/16388367/fesom26rc_ice_fct_screening.pdf)

**Comment by JanStreffing** [comment]
Differences are moderate. I would like a second opinion on:
NH vs SH differences
fesom26rc_ice_fct_screening_hslice_ssh_rob

More NH September sea ice both in extent and thickness at the margins:
fesom26rc_ice_fct_screening_hslice_np_m_ice_nps_m9
fesom26rc_ice_fct_screening_hslice_np_a_ice_nps_m9

Slight Changes in NH winter MLD:
fesom26rc_ice_fct_screening_hslice_np_MLD2_nps_m3

About 10% thicker sea ice in SH as well:

fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m9
fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m9
fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m3
fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m3

And slightly shallower mixed layer in austral winter:
fesom26rc_ice_fct_screening_hslice_sp_MLD2_sps_m9

Colder Arctic at middle depths is an improvement, as seen by comparing to clim
fesom26rc_ice_fct_screening_hovm_temp_Arctic_Basin
fesom26rc_ice_fct_screening_hovm_clim_temp_Arctic_Basin

AMOC is weaker and slightly further north:
fesom26rc_ice_fct_screening_zmoc_amoc


If you want to see more, look in the pdf document above!

**Comment by dsidoren** [comment]
> Differences are moderate. I would like a second opinion on: NH vs SH differences fesom26rc_ice_fct_screening_hslice_ssh_rob
> 
> More NH September sea ice both in extent and thickness at the margins: fesom26rc_ice_fct_screening_hslice_np_m_ice_nps_m9 fesom26rc_ice_fct_screening_hslice_np_a_ice_nps_m9
> 
> Slight Changes in NH winter MLD: fesom26rc_ice_fct_screening_hslice_np_MLD2_nps_m3
> 
> About 10% thicker sea ice in SH as well:
> 
> fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m9 fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m9 fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m3 fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m3
> 
> And slightly shallower mixed layer in austral winter: fesom26rc_ice_fct_screening_hslice_sp_MLD2_sps_m9
> 
> Colder Arctic at middle depths might be an improvement, as seen by comparing to clim. Hard to say due to transient forcing and AA. fesom26rc_ice_fct_screening_hovm_temp_Arctic_Basin fesom26rc_ice_fct_screening_hovm_clim_temp_Arctic_Basin
> 
> AMOC is weaker and slightly further north: fesom26rc_ice_fct_screening_zmoc_amoc
> 
> If you want to see more, look in the pdf document above!



> Differences are moderate. I would like a second opinion on: NH vs SH differences fesom26rc_ice_fct_screening_hslice_ssh_rob
> 
> More NH September sea ice both in extent and thickness at the margins: fesom26rc_ice_fct_screening_hslice_np_m_ice_nps_m9 fesom26rc_ice_fct_screening_hslice_np_a_ice_nps_m9
> 
> Slight Changes in NH winter MLD: fesom26rc_ice_fct_screening_hslice_np_MLD2_nps_m3
> 
> About 10% thicker sea ice in SH as well:
> 
> fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m9 fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m9 fesom26rc_ice_fct_screening_hslice_sp_m_ice_sps_m3 fesom26rc_ice_fct_screening_hslice_sp_a_ice_sps_m3
> 
> And slightly shallower mixed layer in austral winter: fesom26rc_ice_fct_screening_hslice_sp_MLD2_sps_m9
> 
> Colder Arctic at middle depths might be an improvement, as seen by comparing to clim. Hard to say due to transient forcing and AA. fesom26rc_ice_fct_screening_hovm_temp_Arctic_Basin fesom26rc_ice_fct_screening_hovm_clim_temp_Arctic_Basin
> 
> AMOC is weaker and slightly further north: fesom26rc_ice_fct_screening_zmoc_amoc
> 
> If you want to see more, look in the pdf document above!

It looks like the changes are indeed small. The modifications in FCT screening lead to a change in sea ice that is less dissipative. This results in a slightly shallower MLD in the LS due to the change in sea ice export. The rest of the signal seems to be a consequence of this effect. I would suggest that the change in results is minor, but the screening should preferably take into account the min/max from the previous timestep. I would merge it!

**Pull request merged**
