### PR TITLE
Refactoring better metadata

### PR DESCRIPTION
**Pull request by pgierz**
Replacement for #300, as my private fork was somehow messed up.

### CODE REVIEW

**Comment by pgierz** [comment]
More to do before merge: remove the "2" files created by my cloud backup. Sorry about that

**Comment by pgierz** [comment]
Hi @koldunovn: this is good to go from my side. I restored the old dimension names `nod2` and `elem` instead of `nnode` and `nface` (that was the example on the U-Grid website); but that would have broken a ton of downstream tools. Maybe it is nicer not to do that ;-)

**Comment by koldunovn** [comment]
@pgierz Are we missing location of the centers of elements in `fesom.mesh.diag.nc`?

**Comment by pgierz** [comment]
Should we have those as well? I can add it. The ugrid check passes, but if it useful no problem to include it.

**Comment by koldunovn** [comment]
@pgierz That would be great! I don't think we should limit ourselves by ugrid minimum, and I would add as much info as possible, ideally most of the things from the mesh object :)

**Comment by JanStreffing** [comment]
@pgierz will have time to look at this in April. Either we can resolve the MR conflict by ourselves or we need to push this MR to the next release.

**Review by JanStreffing — APPROVED** [review]

**Pull request merged**
