### PR TITLE
Workbench merge cavity

### PR DESCRIPTION
**Pull request by patrickscholz**
Hey Dima, my early Chrismas Present to you, happy merging, Ho Ho Ho ?!

- merge CAVITY into master: 

- so far CAVITY works well with linfs, for zstar and zlevel issue below need to be solved

- there is still an open issue with computing PGF via density (without cavity-ocean pressure boundary condition), the PGF computation via pressure (Sergeys Idea) seems to work

### CODE REVIEW

**Comment by patrickscholz** [comment]
found a bug next try

**Comment by koldunovn** [comment]
@patrickscholz do you think we need to change results of the tests, or you will try to reproduce the old values with your code?

**Comment by dsidoren** [comment]
> Hey Dima, my early Chrismas Present to you, happy merging, Ho Ho Ho ?!
> 
> * merge CAVITY into master:
> * so far CAVITY works well with linfs, for zstar and zlevel issue below need to be solved
> * there is still an open issue with computing PGF via density (without cavity-ocean pressure boundary condition), the PGF computation via pressure (Sergeys Idea) seems to work

Patrick,  I went through the code, looks cool. Due to the large amount of changes, however, there is no chance to detect any error but it is clear what you did. The tests, however, failed. How shall we proceed? What could be the reason for failing?

**Comment by patrickscholz** [comment]
@dsidoren , @koldunovn
Hi Nikolay and Dima, we have to postpone the merging of the cavity stuff for sure, i have played around with my cavity code and zstar playing with different PGFs and realized that something is not ok with that code. The code is rather instable and tends to blow, where it should not blowup. So i will go again through all the cavity stuff step by step to isolate the issue. 
Ho, Ho, Ho merry christmas 

Mfg

Patrick

**Comment by patrickscholz** [comment]
@dsidoren  and @koldunovn 
Hi Dima and Nikolay 

So i rechecked my Cavity stuff and found the bug that messes the things up. I also checked over Christmas if there are any strange features/biases of the new code compared to the old one (master). Except the typical random background bias pattern of ollie i couldn't find any additional major biases the poke out of the background bias. So I think the branch could be merged.

**Pull request merged**
