### PR TITLE
Cycle3 updates branch vs refactoring

### PR DESCRIPTION
**Pull request by trackow**
This is to get an idea how the branches differ and shouldn't be merged in this state

### CODE REVIEW

**Comment by JanStreffing** [comment]
@trackow As above

**Comment by JanStreffing** [comment]
@trackow "shouldn't be merged in this state". Is this still the case? We had added this branch to the 2.6 Todo list.

**Review by patrickscholz — APPROVED** [review]

**Review by patrickscholz — APPROVED** [review]

**Comment by trackow** [comment]
The extra fields in [src/gen_modules_diag.F90](https://github.com/FESOM/fesom2/pull/434#diff-16a3efdab04a8b3fcf618d2024bbd7b6562803f33475374f0299eddd428b29b2) might be good to have, and then to add them in ifs_interface, but the rest of the changes seem outdated/dangerous to me. Closing this for the moment

**Comment by JanStreffing** [comment]
Perhaps you can extract the changes that you think are still relevant into a separate branch and merge request.

**Pull request closed without merging**
