### PR TITLE
refactoring with icebergs

### PR DESCRIPTION
**Pull request by ackerlar**

### CODE REVIEW

**Comment by JanStreffing** [comment]
Hello @ackerlar, thank you for putting this PR together. Quite a big one! I did a scan of the PR, and I would recommend a general cleanup of

- unused subroutines
- comments with data and author of single lines
- disused debug output

I found one line where the oifs and ifs setups were inadvertently modified.  Besides that the merge conflicts have to be resolved of course. Overall a great step forward. Let me know if you have some questions / would like some help. I'd happily sit together for an our or so, getting this one on track.

**Comment by JanStreffing** [comment]
I had a quick chat about this one with @patrickscholz. Most of the merge conflicts are trivial. Only the one in  src/fesom_module.F90  looks to be a bit more complex. Maybe you can do the others ones yourself, and if you get stuck with  src/fesom_module.F90, Patrick or me try to help out.

**Comment by ackerlar** [comment]
All checks seem to work with the latest commit. Is there anything I need to do now?

**Comment by JanStreffing** [comment]
> All checks seem to work with the latest commit. Is there anything I need to do now?

You still need to request a review.

**Review by JanStreffing — APPROVED** [review]

**Pull request merged**
